import type { MenuItem } from "./types"

export const lomoMenu: MenuItem[] = [
  {
    id: "lomo-1",
    name: "SUPERCHARGER",
    price: 23500,
    image: "/images/supercharger.png",
    category: "lomo",
    popular: true,
    description:
      "Pan napolitano de 33cm de elaboración propia, doble lomo, queso, jamón, huevos, tomates, lechuga, mayonesa artesanal saborizada y doble porción de fritas.",
  },
  {
    id: "lomo-2",
    name: "SR. LOMO",
    price: 18000,
    image: "/images/sr-lomo.png",
    category: "lomo",
    description:
      "Pan napolitano de 25cm de elaboración propia, lomo, queso, jamón, huevos, tomates. lechuga, mayonesa artesanal saborizada.Con fritas",
  },
  {
    id: "lomo-3",
    name: "SUPER-DUPER",
    price: 16500,
    image: "/images/super-duper.png",
    category: "lomo",
    description:
      "Pan napolitano, carne de ternera, queso, jamón, huevos, tomates, lechuga, mayonesa artesanal saborizada y doble porción de fritas.",
  },
  {
    id: "lomo-4",
    name: "PROMO SUPER-DUPER (COMEN 4)",
    price: 26500,
    image: "/images/super-duper-promo.jpg",
    category: "lomo",
    ingredients: [
      "Pan napolitano, carne de ternera, queso, jamón, huevos, tomates, lechuga, mayonesa artesanal saborizada y doble porción de fritas.",
    ],
  },
  {
    id: "lomo-5",
    name: "MY LUXURY",
    price: 10500,
    image: "/images/luxury.jpeg",
    category: "lomo",
  },
  {
    id: "lomo-6",
    name: "PORCIÓN DE FRITAS CON ADEREZO",
    price: 7000,
    image: "/images/papas.jpeg",
    category: "lomo",
  },
  {
    id: "lomo-7",
    name: "MAYONESA DE AJO",
    price: 3000,
    image: "/images/mayonesa-ajo.png",
    category: "lomo",
  },
  {
    id: "lomo-8",
    name: "MAYONESA DE LIMON",
    price: 3000,
    image: "/images/mayonesa-limon.png",
    category: "lomo",
  },
]

export const burgerMenu: MenuItem[] = [
  {
    id: "Proximamente",
    name: "Proximamente",
    price: 0,
    image: "/images/gra-hamburguesa-logo.jpg",
    category: "burger",
    popular: true,
    ingredients: ["Proximamente"],
  },
]

export const empanadaMenu: MenuItem[] = [
  {
    id: "empanada-1",
    name: "Arabes Docena",
    price: 15500,
    image: "/images/sra-empanada.png",
    category: "empanada",
    popular: true,
    priceLabel: "por docena",
  },
  {
    id: "empanada-2",
    name: "Arabes Media Docena ",
    price: 9000,
    image: "/images/sra-empanada.png",
    category: "empanada",
    priceLabel: "media docena",
  },
  {
    id: "empanada-3",
    name: "Arabes Unidad",
    price: 1550,
    image: "/images/sra-empanada.png",
    category: "empanada",
    priceLabel: "por unidad",
  },
  {
    id: "empanada-4",
    name: "JAMÓN Y MOZZARELLA Docena",
    price: 14500,
    image: "/images/jamon-mozzarella-new.png",
    category: "empanada",
    priceLabel: "por docena",
  },
  {
    id: "empanada-5",
    name: "JAMÓN Y MOZZARELLA Media Docena",
    price: 8500,
    image: "/images/jamon-mozzarella-new.png",
    category: "empanada",
    priceLabel: "media docena",
  },
  {
    id: "empanada-6",
    name: "JAMÓN Y MOZZARELLA Unidad",
    price: 1450,
    image: "/images/jamon-mozzarella-new.png",
    category: "empanada",
    priceLabel: "por unidad",
  },
  {
    id: "empanada-7",
    name: "QUESO ROQUEFORT Docena",
    price: 15500,
    image: "/images/queso-roquefort.png",
    category: "empanada",
    popular: true,
    priceLabel: "por docena",
  },
  {
    id: "empanada-8",
    name: "QUESO ROQUEFORT Media Docena",
    price: 9000,
    image: "/images/queso-roquefort.png",
    category: "empanada",
    priceLabel: "media docena",
  },
  {
    id: "empanada-9",
    name: "QUESO ROQUEFORT Unidad",
    price: 1550,
    image: "/images/queso-roquefort.png",
    category: "empanada",
    priceLabel: "por unidad",
  },
  {
    id: "empanada-10",
    name: "CAPRESSE Docena",
    price: 13500,
    image: "/images/caprese-new.jpg",
    category: "empanada",
    popular: true,
    priceLabel: "por docena",
  },
  {
    id: "empanada-11",
    name: "CAPRESSE Media Docena",
    price: 7500,
    image: "/images/caprese-new.jpg",
    category: "empanada",
    priceLabel: "media docena",
  },
  {
    id: "empanada-12",
    name: "CAPRESSE Unidad",
    price: 1350,
    image: "/images/caprese-new.jpg",
    category: "empanada",
    priceLabel: "por unidad",
  },
]

export const pizzaMenu: MenuItem[] = [
  {
    id: "pizza-1",
    name: "MOZZARELLA",
    price: 12500,
    image: "/images/mozzarella-pizza.png",
    category: "pizza",
    popular: true,
  },
  {
    id: "pizza-2",
    name: "FUGAZZA",
    price: 10500,
    image: "/images/fugazza-especial.png",
    category: "pizza",
  },
  {
    id: "pizza-3",
    name: "FUGAZZETA",
    price: 13500,
    image: "/images/fugazzeta-final.png",
    category: "pizza",
  },
  {
    id: "pizza-4",
    name: "CALABRESA",
    price: 13500,
    image: "/images/calabresa-pizza.png",
    category: "pizza",
  },
  {
    id: "pizza-5",
    name: "NAPOLITANA",
    price: 12500,
    image: "/images/napolitana-pizza.png",
    category: "pizza",
  },
  {
    id: "pizza-6",
    name: "ROQUEFORT",
    price: 13600,
    image: "/images/roquefort-pizza-new.png",
    category: "pizza",
  },
  {
    id: "pizza-7",
    name: "ESPECIAL CON ANCHOAS ",
    price: 15500,
    image: "/images/anchoas-especial-new.png",
    category: "pizza",
  },
  {
    id: "pizza-8",
    name: "ESPECIAL CON JAMON NATURAL Y MORRONES",
    price: 14000,
    image: "/images/morrones-especial.png",
    category: "pizza",
  },
]

export const dessertMenu: MenuItem[] = [
  {
    id: "dessert-1",
    name: "Flan Casero",
    price: 3500,
    image: "/images/flan-casero.jpg",
    category: "dessert",
    popular: true,
  },
  {
    id: "dessert-2",
    name: "BÚDIN DE PAN CON PASAS DE UVA SIN SEMILLAS",
    price: 3500,
    image: "/images/budin-pan-pasas.jpg",
    category: "dessert",
    popular: true,
  },
  {
    id: "dessert-3",
    name: "BÚDIN DE PAN SIN PASAS",
    price: 3500,
    image: "/images/budin-pan-sin-pasas.jpg",
    category: "dessert",
  },
  {
    id: "dessert-4",
    name: "PALITO BOMBÓN HELADO DE DULCE DE LECHE",
    price: 1200,
    image: "/images/palito-bombon-dulce-de-leche.jpg",
    category: "dessert",
    popular: true,
  },
  {
    id: "dessert-5",
    name: "PALITO BOMBÓN HELADO DE CREMA AMERICANA",
    price: 1200,
    image: "/images/palito-bombon-crema-americana.jpg",
    category: "dessert",
  },
  {
    id: "dessert-6",
    name: "BOMBÓN SUIZO",
    price: 2200,
    image: "/images/bombon-suizo.jpg",
    category: "dessert",
  },
  {
    id: "dessert-7",
    name: "BOMBÓN ESCOCÉS",
    price: 2200,
    image: "/images/58819412-3b65-49b2-8ee5.jpeg",
    category: "dessert",
  },
  {
    id: "dessert-8",
    name: "TACITA COMBI - DULCE DE LECHE",
    price: 2200,
    image: "/images/whatsapp-20image-202025-12-31-20at-203.jpeg",
    category: "dessert",
    description: "Tacita con dulce de leche",
  },
  {
    id: "dessert-9",
    name: "TACITA COMBI - CHOCOLATE",
    price: 2200,
    image: "/images/whatsapp-20image-202025-12-31-20at-203.jpeg",
    category: "dessert",
    description: "Tacita con chocolate",
  },
  {
    id: "dessert-10",
    name: "TACITA COMBI - FRUTILLA",
    price: 2200,
    image: "/images/whatsapp-20image-202025-12-31-20at-203.jpeg",
    category: "dessert",
    description: "Tacita con frutilla",
  },
]

export const paymentMethods = [
  {
    id: "transfer",
    name: "Transferencia Bancaria",
    icon: "🏦",
    description: "ALIAS: SR.LOMO.VCP",
    enabled: true,
  },
  {
    id: "cash",
    name: "Efectivo",
    icon: "💵",
    description: "Pago contra entrega",
    enabled: true,
  },
]
