import type { MenuItem } from "./types"

export const lomoMenu: MenuItem[] = [
  {
    id: "lomo-1",
    name: "SUPERCHARGER",
    price: 27000,
    image: "/images/supercharger.png",
    category: "lomo",
    popular: true,
    description:
      "Pan napolitano de 33cm de elaboración propia, doble lomo, queso, jamón, huevos, tomates, lechuga, mayonesa artesanal saborizada y doble porción de fritas.",
  },
  {
    id: "lomo-2",
    name: "SR. LOMO",
    price: 20500,
    image: "/images/sr-lomo.png",
    category: "lomo",
    description:
      "Pan napolitano de 25cm de elaboración propia, lomo, queso, jamón, huevos, tomates. lechuga, mayonesa artesanal saborizada.Con fritas",
  },
  {
    id: "lomo-3",
    name: "SUPER-DUPER",
    price: 19500,
    image: "/images/super-duper.png",
    category: "lomo",
    description:
      "Pan napolitano, carne de ternera, queso, jamón, huevos, tomates, lechuga, mayonesa artesanal saborizada y lluvia de fritas",
  },
  {
    id: "lomo-4",
    name: "PROMO SUPER-DUPER (COMEN 4)",
    price: 32000,
    image: "/images/super-duper-promo.jpg",
    category: "lomo",
    ingredients: [
      "Pan napolitano, carne de ternera, queso, jamón, huevos, tomates, lechuga, mayonesa artesanal saborizada y doble lluvia de fritas.",
    ],
  },
  {
    id: "lomo-5",
    name: "MY LUXURY",
    price: 11500,
    image: "/images/luxury.jpeg",
    category: "lomo",
  },
  {
    id: "lomo-6",
    name: "PORCIÓN DE FRITAS CON ADEREZO",
    price: 10000,
    image: "/images/papas.jpeg",
    category: "lomo",
  },
  {
    id: "lomo-7",
    name: "MAYONESA DE AJO",
    price: 3500,
    image: "/images/mayonesa-ajo.png",
    category: "lomo",
  },
  {
    id: "lomo-8",
    name: "MAYONESA DE LIMON",
    price: 3500,
    image: "/images/mayonesa-limon.png",
    category: "lomo",
  },
]

export const burgerMenu: MenuItem[] = [
  
  {
    id: "burger-1",
    name: "SRA.HAMBURGUESA COMPLETA",
    price: 11500,
    image: "/images/hamb-simple.jpg",
    category: "burger",
    popular: true,
    description: "Pan Tipo Napolitano, un Medallón de carne de 100gr con un Blend exclusivo, Queso Cheddar de Primera calidad, Tomate Fresco en rodajas, Lechuga Fresca, tres aderezos a elección y pan.",
    sauceOptions: ["Mayonesa Clásica", "Ketchup", "Mostaza"],
  },
  {
    id: "burger-2",
    name: "HAMB SUPERCHARGER",
    price: 16000,
    image: "/images/hamb-supercharger.jpg",
    category: "burger",
    description: "Pan Tipo Napolitano, Dos Medallones de carne de 100gr con un Blend exclusivo, Doble Queso Cheddar de Primera calidad, Tomate Fresco en rodajas, Lechuga Fresca, tres aderezos a elección y pan.",
    sauceOptions: ["Mayonesa Clásica", "Ketchup", "Mostaza"],
  },
  {
    id: "burger-2",
    name: "HAMBURPIZZA",
    price: 30000,
    image: "/images/hamburpizza.jpg",
    category: "burger",
    sauceOptions: ["Mayonesa Clásica", "Ketchup", "Mostaza"],
  },
]

export const empanadaMenu: MenuItem[] = [
  {
    id: "empanada-1",
    name: "Arabes Docena",
    price: 18500,
    image: "/images/sra-empanada.png",
    category: "empanada",
    popular: true,
    priceLabel: "por docena",
  },
  {
    id: "empanada-2",
    name: "Arabes Media Docena ",
    price: 10000,
    image: "/images/sra-empanada.png",
    category: "empanada",
    priceLabel: "media docena",
  },
  {
    id: "empanada-3",
    name: "Arabes Unidad",
    price: 1850,
    image: "/images/sra-empanada.png",
    category: "empanada",
    priceLabel: "por unidad",
  },
  {
    id: "empanada-4",
    name: "JAMÓN Y MOZZARELLA Docena",
    price: 14500,
    image: "/images/jamon-mozzarella-new.png",
    category: "empanada",
    priceLabel: "por docena",
  },
  {
    id: "empanada-5",
    name: "JAMÓN Y MOZZARELLA Media Docena",
    price: 8000,
    image: "/images/jamon-mozzarella-new.png",
    category: "empanada",
    priceLabel: "media docena",
  },
  {
    id: "empanada-6",
    name: "JAMÓN Y MOZZARELLA Unidad",
    price: 1450,
    image: "/images/jamon-mozzarella-new.png",
    category: "empanada",
    priceLabel: "por unidad",
  },
  {
    id: "empanada-7",
    name: "QUESO ROQUEFORT Docena",
    price: 16000,
    image: "/images/queso-roquefort.png",
    category: "empanada",
    popular: true,
    priceLabel: "por docena",
  },
  {
    id: "empanada-8",
    name: "QUESO ROQUEFORT Media Docena",
    price: 8500,
    image: "/images/queso-roquefort.png",
    category: "empanada",
    priceLabel: "media docena",
  },
  {
    id: "empanada-9",
    name: "QUESO ROQUEFORT Unidad",
    price: 1600,
    image: "/images/queso-roquefort.png",
    category: "empanada",
    priceLabel: "por unidad",
  },
  {
    id: "empanada-10",
    name: "CAPRESSE Docena",
    price: 13500,
    image: "/images/caprese-new.jpg",
    category: "empanada",
    popular: true,
    priceLabel: "por docena",
  },
  {
    id: "empanada-11",
    name: "CAPRESSE Media Docena",
    price: 7500,
    image: "/images/caprese-new.jpg",
    category: "empanada",
    priceLabel: "media docena",
  },
  {
    id: "empanada-12",
    name: "CAPRESSE Unidad",
    price: 1350,
    image: "/images/caprese-new.jpg",
    category: "empanada",
    priceLabel: "por unidad",
  },
]

export const pizzaMenu: MenuItem[] = [
  {
    id: "pizza-1",
    name: "MOZZARELLA",
    price: 13000,
    image: "/images/mozzarella-pizza.png",
    category: "pizza",
    popular: true,
  },
  {
    id: "pizza-2",
    name: "FUGAZZA",
    price: 11500,
    image: "/images/fugazza-especial.png",
    category: "pizza",
  },
  {
    id: "pizza-3",
    name: "FUGAZZETA",
    price: 14000,
    image: "/images/fugazzeta-final.png",
    category: "pizza",
  },
  {
    id: "pizza-4",
    name: "CALABRESA",
    price: 14000,
    image: "/images/calabresa-pizza.png",
    category: "pizza",
  },
  {
    id: "pizza-5",
    name: "NAPOLITANA",
    price: 13500,
    image: "/images/napolitana-pizza.png",
    category: "pizza",
  },
  {
    id: "pizza-6",
    name: "ROQUEFORT",
    price: 16000,
    image: "/images/roquefort-pizza-new.png",
    category: "pizza",
  },
  {
    id: "pizza-7",
    name: "ESPECIAL CON ANCHOAS ",
    price: 15500,
    image: "/images/anchoas-especial-new.png",
    category: "pizza",
  },
  {
    id: "pizza-8",
    name: "ESPECIAL CON JAMON NATURAL Y MORRONES",
    price: 14500,
    image: "/images/morrones-especial.png",
    category: "pizza",
  },
  {
    id: "burger-2",
    name: "HAMBURPIZZA",
    price: 30000,
    image: "/images/hamburpizza.jpg",
    category: "burger",
    sauceOptions: ["Mayonesa Clásica", "Ketchup", "Mostaza"],
  },
  {
    id: "pizza-8",
    name: "PIZZA DE PALMITOS",
    price: 19500,
    image: "/images/pal.jpg",
    category: "pizza",
  },
  {
    id: "pizza-8",
    name: "TROPICAL CON ANANA Y CEREZAS",
    price: 22500,
    image: "/images/fniu.jpg",
    category: "pizza",
  },
  {
    id: "pizza-8",
    name: "ESPECIAL CON HUEVO",
    price: 16000,
    image: "/images/pizzaaaaaaaaaaa.jpg",
    category: "pizza",
  },
  {
    id: "pizza-8",
    name: "PIZZA PEPERONATA",
    price: 16500,
    image: "/images/pepero.jpg",
    category: "pizza",
  },
]

export const dessertMenu: MenuItem[] = [
  {
    id: "dessert-4",
    name: "PALITO BOMBÓN HELADO DE DULCE DE LECHE",
    price: 1200,
    image: "/images/palito-bombon-dulce-de-leche.jpg",
    category: "dessert",
    popular: true,
  },
  {
    id: "dessert-5",
    name: "PALITO BOMBÓN HELADO DE CREMA AMERICANA",
    price: 1200,
    image: "/images/palito-bombon-crema-americana.jpg",
    category: "dessert",
  },
  {
    id: "dessert-6",
    name: "BOMBÓN SUIZO",
    price: 2200,
    image: "/images/bombon-suizo.jpg",
    category: "dessert",
  },
  {
    id: "dessert-7",
    name: "BOMBÓN ESCOCÉS",
    price: 2200,
    image: "/images/58819412-3b65-49b2-8ee5.jpeg",
    category: "dessert",
  },
  {
    id: "dessert-8",
    name: "TACITA COMBI - DULCE DE LECHE",
    price: 2200,
    image: "/images/whatsapp-20image-202025-12-31-20at-203.jpeg",
    category: "dessert",
    description: "Tacita con dulce de leche",
  },
  {
    id: "dessert-9",
    name: "TACITA COMBI - CHOCOLATE",
    price: 2200,
    image: "/images/whatsapp-20image-202025-12-31-20at-203.jpeg",
    category: "dessert",
    description: "Tacita con chocolate",
  },
  {
    id: "dessert-10",
    name: "TACITA COMBI - FRUTILLA",
    price: 2200,
    image: "/images/whatsapp-20image-202025-12-31-20at-203.jpeg",
    category: "dessert",
    description: "Tacita con frutilla",
  },
]

export const comboMenu: MenuItem[] = [
  {
    id: "combo-1",
    name: "1 MY LUXURY + 1 BOMBÓN ESCOCÉS O SUIZO",
    price: 13700,
    image: "/images/combo-luxury-burger.jpeg",
    category: "combo",
    popular: true,
  },
  {
    id: "combo-2",
    name: "2 MY LUXURY + 2 BOMBÓN ESCOCÉS O SUIZO",
    price: 27400,
    image: "/images/combo-luxury-burger.jpeg",
    category: "combo",
  },
  {
    id: "combo-3",
    name: "MUZZARELLA + 6 EMPANADAS ARABES ",
    price: 23000,
    image: "/images/combo-muzzarella-pizza.jpeg",
    category: "combo",
  },
  {
    id: "combo-3",
    name: "1 SUPERCHARGER + 2 BOMBÓN ESCOCÉS O SUIZO ",
    price: 32400,
    image: "/images/combo-supercharger.jpeg",
    category: "combo",
  },
  {
    id: "combo-4",
    name: "1 MUZZARELLA + 1 ESPECIAL",
    price: 28500,
    image: "/images/combo-muzzarella-pizza.jpeg",
    category: "combo",
  },
  {
    id: "combo-5",
    name: "1 SR.LOMO + 2 BOMBÓN ESCOCÉS O SUIZO ",
    price: 24900,
    image: "/images/combo-sr-lomo.jpeg",
    category: "combo",
    popular: true,
  },
]

export const bebidaMenu: MenuItem[] = [
  {
    id: "bebida-1",
    name: "COCA-COLA 2.50L",
    price: 5800,
    image: "/images/coca-cola-2500ml.png",
    category: "bebida",
    popular: true,
  },
  {
    id: "bebida-2",
    name: "COCA-COLA 1.5L",
    price: 4600,
    image: "/images/coca-cola-1500ml.png",
    category: "bebida",
  },
  {
    id: "bebida-3",
    name: "FERNET BRANCA 750ML",
    price: 17000,
    image: "/images/fernet-branca.png",
    category: "bebida",
  },
  {
    id: "bebida-4",
    name: "PRITTY 1.5L",
    price: 3000,
    image: "/images/pritty-limon.png",
    category: "bebida",
  },
  {
    id: "bebida-5",
    name: "VINO TINTO TORO EN CAJA 1L",
    price: 3500,
    image: "/images/vino-toro-tinto.png",
    category: "bebida",
  },
  {
    id: "bebida-6",
    name: "COMBO BRANCA",
    price: 26000,
    image: "/images/combo-branca.jpeg",
    category: "bebida",
  },
  {
    id: "bebida-7",
    name: "COMBO PRITEADO",
    price: 7500,
    image: "/images/combo-priteado.jpeg",
    category: "bebida",
  },
  {
    id: "bebida-8",
    name: "HIELO",
    price: 3000,
    image: "/images/bolsa-hielo.jpeg",
    category: "bebida",
  },

]

export const paymentMethods = [
  {
    id: "transfer",
    name: "Transferencia Bancaria",
    icon: "🏦",
    description: "ALIAS: SR.LOMO.VCP",
    enabled: true,
  },
  {
    id: "cash",
    name: "Efectivo",
    icon: "💵",
    description: "Pago contra entrega",
    enabled: true,
  },
]
